version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3333:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wallet
